<?php require('header.php') ?>
<div class="grid_6 alpha">
    <h1>Welcome to Better Phones</h1>
    <p>Here at <strong>Better Phones</strong> we're all about getting you the phone 
        that you want and need. Are you tired of all your friends having better phones 
        than you? Well no longer should that be a problem. We can get you a great new 
        phone at a low cost.
    </p>
    <p>Want to know what's the hype around the iPhone? Too bad! We don't sell them. 
        Instead we sell you the best of the rest and our top of the range phones prove
        that you don't need an iPhone to be cool.</p>
    <p>Browse our site and register for an account to get your better phone today!</p>
</div>
<img src="images/lumia.png" class="grid_2" />
<div class="grid_4 omega">
    <h1>New Models</h1>
    <h2>Nokia Lumia 800</h2>
    <p>Our newest phone on sale is the Nokia Lumia 800. This is one of the 
    premium Windows Phone handsets out there. It's generated quite a buzz and 
    we think you should check it out.</p>
    <p><a href="viewitem.php?id=30">Find out More</a></p>
</div>
<?php require('footer.phtml') ?>
